#!/bin/bash

entries=" Shutdown\n Reboot\n鈴 Suspend \n Standby\n Logout\n Lockscreen"

selected=$(echo -e $entries|wofi --dmenu -W 250 -H 250 --location 3 -x -51 -y 6 -k /dev/null | awk '{print tolower($2)}')

case $selected in
  shutdown)
    loginctl poweroff;;
  reboot)
    loginctl reboot;;
  suspend)
    loginctl suspend;;
  standby)
    sleep 1 && hyprctl dispatch dpms off;;
  logout)
    loginctl terminate-session ${XDG_SESSION_ID-};;
  lockscreen)
    swaylock;;
esac
